In [1]:
import pandas as pd

In [2]:


df = pd.read_csv(
    r'C:\my_da_projects\unified_projects_2\APL_Logistics.csv',
    encoding='latin1'
)

In [3]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [4]:
df.columns=df.columns.str.replace(' ','_')

In [5]:
df.head()

,Type,Days_for_shipping_(real),Days_for_shipment_(scheduled),Benefit_per_order,Sales_per_customer,Delivery_Status,Late_delivery_risk,Category_Id,Category_Name,Customer_City,...,Order_Item_Quantity,Sales,Order_Item_Total,Order_Profit_Per_Order,Order_Region,Order_State,Order_Status,Product_Name,Product_Price,Shipping_Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [6]:
df.columns=df.columns.str.lower()

In [7]:
df.head()

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,product_name,product_price,shipping_mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [8]:
df.describe()

,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,late_delivery_risk,category_id,customer_id,customer_zipcode,department_id,latitude,...,order_customer_id,order_item_discount,order_item_discount_rate,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,product_price
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,3.497654,2.931847,21.974989,183.107607,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,6691.379495,20.664741,0.101668,141.232547,0.120647,2.127638,203.772092,183.107607,21.974989,141.232547
std,1.623722,1.374449,104.433526,120.043668,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,4162.918106,21.800901,0.070415,139.732489,0.466796,1.453451,132.273075,120.043668,104.433526,139.732489
min,0.000000,0.000000,-4274.980000,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,0.000000,0.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.980000,9.990000
25%,2.000000,2.000000,7.000000,104.380000,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,3258.500000,5.400000,0.040000,50.000000,0.080000,1.000000,119.980000,104.380000,7.000000,50.000000
50%,3.000000,4.000000,31.520000,163.990000,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,6457.000000,14.000000,0.100000,59.990000,0.270000,1.000000,199.920000,163.990000,31.520000,59.990000
75%,5.000000,4.000000,64.800000,247.400000,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,9779.000000,29.990000,0.160000,199.990000,0.360000,3.000000,299.950000,247.400000,64.800000,199.990000
max,6.000000,4.000000,911.800000,1939.990000,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,20757.000000,500.000000,0.250000,1999.990000,0.500000,5.000000,1999.990000,1939.990000,911.800000,1999.990000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   type                           180519 non-null  object
 1   days_for_shipping_(real)       180519 non-null  int64
 2   days_for_shipment_(scheduled)  180519 non-null  int64
 3   benefit_per_order              180519 non-null  float64
 4   sales_per_customer             180519 non-null  float64
 5   delivery_status                180519 non-null  object
 6   late_delivery_risk             180519 non-null  int64
 7   category_id                    180519 non-null  int64
 8   category_name                  180519 non-null  object
 9   customer_city                  180519 non-null  object
 10  customer_country               180519 non-null  object
 11  customer_fname                 180519 non-null  object
 12  customer_id                    180519 non-null  int64
 13  customer_lname                 180511 non-null  object
 14  customer_segment               180519 non-null  object
 15  customer_state                 180519 non-null  object
 16  customer_street                180519 non-null  object
 17  customer_zipcode               180516 non-null  float64
 18  department_id                  180519 non-null  int64
 19  department_name                180519 non-null  object
 20  latitude                       180519 non-null  float64
 21  longitude                      180519 non-null  float64
 22  market                         180519 non-null  object
 23  order_city                     180519 non-null  object
 24  order_country                  180519 non-null  object
 25  order_customer_id              180519 non-null  int64
 26  order_item_discount            180519 non-null  float64
 27  order_item_discount_rate       180519 non-null  float64
 28  order_item_product_price       180519 non-null  float64
 29  order_item_profit_ratio        180519 non-null  float64
 30  order_item_quantity            180519 non-null  int64
 31  sales                          180519 non-null  float64
 32  order_item_total               180519 non-null  float64
 33  order_profit_per_order         180519 non-null  float64
 34  order_region                   180519 non-null  object
 35  order_state                    180519 non-null  object
 36  order_status                   180519 non-null  object
 37  product_name                   180519 non-null  object
 38  product_price                  180519 non-null  float64
 39  shipping_mode                  180519 non-null  object
dtypes: float64(13), int64(8), object(19)
memory usage: 55.1+ MB

In [10]:
df.isnull().sum()

type                             0
days_for_shipping_(real)         0
days_for_shipment_(scheduled)    0
benefit_per_order                0
sales_per_customer               0
delivery_status                  0
late_delivery_risk               0
category_id                      0
category_name                    0
customer_city                    0
customer_country                 0
customer_fname                   0
customer_id                      0
customer_lname                   8
customer_segment                 0
customer_state                   0
customer_street                  0
customer_zipcode                 3
department_id                    0
department_name                  0
latitude                         0
longitude                        0
market                           0
order_city                       0
order_country                    0
order_customer_id                0
order_item_discount              0
order_item_discount_rate         0
order_item_product_price         0
order_item_profit_ratio          0
order_item_quantity              0
sales                            0
order_item_total                 0
order_profit_per_order           0
order_region                     0
order_state                      0
order_status                     0
product_name                     0
product_price                    0
shipping_mode                    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.customer_zipcode

0         78521.0
1         80126.0
2         80126.0
3         80126.0
4         80126.0
           ...
180514      725.0
180515    60544.0
180516      725.0
180517    60402.0
180518    33126.0
Name: customer_zipcode, Length: 180519, dtype: float64

In [13]:
df['customer_zipcode']=df['customer_zipcode'].fillna(df['customer_zipcode'].mean())

In [14]:
df['customer_lname']=df['customer_lname'].fillna('unknown')

In [15]:
df.isnull().sum()

type                             0
days_for_shipping_(real)         0
days_for_shipment_(scheduled)    0
benefit_per_order                0
sales_per_customer               0
delivery_status                  0
late_delivery_risk               0
category_id                      0
category_name                    0
customer_city                    0
customer_country                 0
customer_fname                   0
customer_id                      0
customer_lname                   0
customer_segment                 0
customer_state                   0
customer_street                  0
customer_zipcode                 0
department_id                    0
department_name                  0
latitude                         0
longitude                        0
market                           0
order_city                       0
order_country                    0
order_customer_id                0
order_item_discount              0
order_item_discount_rate         0
order_item_product_price         0
order_item_profit_ratio          0
order_item_quantity              0
sales                            0
order_item_total                 0
order_profit_per_order           0
order_region                     0
order_state                      0
order_status                     0
product_name                     0
product_price                    0
shipping_mode                    0
dtype: int64

In [16]:
df['customer_zipcode'].dtype

dtype('float64')

In [17]:
#Delivery Gap Calculation
#Delay Gap 
df['delay_gap']=df['days_for_shipping_(real)']-df['days_for_shipment_(scheduled)']

In [18]:
df.head()

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,product_name,product_price,shipping_mode,delay_gap
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class,2
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class,0
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class,0
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class,2
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class,2

In [19]:
def classification(gap):
    if gap<0:
        return 'early'
    elif gap==0:
        return 'on-time'
    else:
        return 'delayed'
df['delivery_category']=df['delay_gap'].apply(classification)

In [20]:
df['delivery_category'].value_counts()

delivery_category
delayed    103400
early       43366
on-time     33753
Name: count, dtype: int64

In [21]:
df.head()

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_item_total,order_profit_per_order,order_region,order_state,order_status,product_name,product_price,shipping_mode,delay_gap,delivery_category
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class,2,delayed
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class,0,on-time
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class,0,on-time
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class,2,delayed
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class,2,delayed

In [22]:
df=df.rename(columns={'days_for_shipping_(real)': 'actual_shipping_days',
    'days_for_shipment_(scheduled)': 'scheduled_shipping_days'})

In [23]:
df.head()

,type,actual_shipping_days,scheduled_shipping_days,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_item_total,order_profit_per_order,order_region,order_state,order_status,product_name,product_price,shipping_mode,delay_gap,delivery_category
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class,2,delayed
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class,0,on-time
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class,0,on-time
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class,2,delayed
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class,2,delayed

In [24]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [25]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://@localhost\\SQLEXPRESS/supplychain?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [57]:
df.to_sql('supply_cleaned_data', engine, if_exists='replace', index=False)

3

In [26]:
df.to_csv('supply_cleaned_data.csv',index=False)

In [27]:
import os

In [28]:
os.getcwd()

'C:\\Users\\Home'